name: ledger_flutter
description: A Flutter plugin to scan, connect & sign transactions using a Ledger Nano X
version: 0.0.1
homepage: https://github.com/RootSoft/ledger-flutter
repository: https://github.com/RootSoft/ledger-flutter
issue_tracker: https://github.com/RootSoft/ledger-flutter/issues

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_reactive_ble: ^5.0.2
  ledger_usb:
    path: "../ledger-usb"
#  ledger_usb:
#    git:
#      url: https://github.com/RootSoft/ledger-usb.git
#      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
